[package]
name = "game_cap"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.10"
rand = "0.8.4"
bevy-inspector-egui = "0.18.1"
bevy_pancam = "0.8"

[profile.dev.package."*"]
opt-level = 3
